CREATE TABLE suspicious_names (CREATED_TS TIMESTAMP,
                               COMPANY_NAME VARCHAR PRIMARY KEY,
                               COMPANY_ID INT)
    WITH (kafka_topic='suspicious_names',
          partitions=1,
          value_format='JSON',
          timestamp='CREATED_TS');

INSERT INTO suspicious_names (CREATED_TS, COMPANY_NAME, COMPANY_ID) VALUES (CAST(DATESUB(DAYS, 2, FROM_DAYS(UNIX_DATE())) AS TIMESTAMP), 'Verizon', 1);
INSERT INTO suspicious_names (CREATED_TS, COMPANY_NAME, COMPANY_ID) VALUES (CAST(DATESUB(DAYS, 2, FROM_DAYS(UNIX_DATE())) AS TIMESTAMP), 'Spirit Halloween', 2);
INSERT INTO suspicious_names (CREATED_TS, COMPANY_NAME, COMPANY_ID) VALUES (CAST(DATESUB(DAYS, 2, FROM_DAYS(UNIX_DATE())) AS TIMESTAMP), 'Best Buy', 3);

CREATE STREAM transactions (TXN_ID BIGINT, USERNAME VARCHAR, RECIPIENT VARCHAR, AMOUNT DOUBLE, TS TIMESTAMP)
    WITH (kafka_topic='transactions',
          partitions=1,
          value_format='JSON',
          timestamp='TS');

INSERT INTO transactions (TXN_ID, USERNAME, RECIPIENT, AMOUNT, TS) VALUES (9900, 'Abby Normal', 'Verizon', 22.0, CAST(DATESUB(DAYS, 1, FROM_DAYS(UNIX_DATE())) AS TIMESTAMP));
INSERT INTO transactions (TXN_ID, USERNAME, RECIPIENT, AMOUNT, TS) VALUES (12, 'Victor von Frankenstein', 'Tattered Cover', 7.0, TIMESTAMPADD(MINUTES, 10, CAST(DATESUB(DAYS, 1, FROM_DAYS(UNIX_DATE())) AS TIMESTAMP)));
INSERT INTO transactions (TXN_ID, USERNAME, RECIPIENT, AMOUNT, TS) VALUES (13, 'Frau Blücher', 'Peebles', 70.0, TIMESTAMPADD(MINUTES, 20, CAST(DATESUB(DAYS, 1, FROM_DAYS(UNIX_DATE())) AS TIMESTAMP)));
INSERT INTO transactions (TXN_ID, USERNAME, RECIPIENT, AMOUNT, TS) VALUES (9903, 'Abby Normal', 'Verizon', 61.0, TIMESTAMPADD(MINUTES, 30, CAST(DATESUB(DAYS, 1, FROM_DAYS(UNIX_DATE())) AS TIMESTAMP)));
INSERT INTO transactions (TXN_ID, USERNAME, RECIPIENT, AMOUNT, TS) VALUES (9901, 'Abby Normal', 'Spirit Halloween', 83.0, TIMESTAMPADD(MINUTES, 40, CAST(DATESUB(DAYS, 1, FROM_DAYS(UNIX_DATE())) AS TIMESTAMP)));
INSERT INTO transactions (TXN_ID, USERNAME, RECIPIENT, AMOUNT, TS) VALUES (9902, 'Abby Normal', 'Spirit Halloween', 46.0, TIMESTAMPADD(MINUTES, 50, CAST(DATESUB(DAYS, 1, FROM_DAYS(UNIX_DATE())) AS TIMESTAMP)));
INSERT INTO transactions (TXN_ID, USERNAME, RECIPIENT, AMOUNT, TS) VALUES (9904, 'Abby Normal', 'Spirit Halloween', 59.0, TIMESTAMPADD(MINUTES, 60, CAST(DATESUB(DAYS, 1, FROM_DAYS(UNIX_DATE())) AS TIMESTAMP)));
INSERT INTO transactions (TXN_ID, USERNAME, RECIPIENT, AMOUNT, TS) VALUES (6, 'Victor von Frankenstein', 'Confluent Cloud', 21.0, TIMESTAMPADD(MINUTES, 70, CAST(DATESUB(DAYS, 1, FROM_DAYS(UNIX_DATE())) AS TIMESTAMP)));
INSERT INTO transactions (TXN_ID, USERNAME, RECIPIENT, AMOUNT, TS) VALUES (18, 'Frau Blücher', 'Target', 70.0, TIMESTAMPADD(MINUTES, 80, CAST(DATESUB(DAYS, 1, FROM_DAYS(UNIX_DATE())) AS TIMESTAMP)));
INSERT INTO transactions (TXN_ID, USERNAME, RECIPIENT, AMOUNT, TS) VALUES (7, 'Victor von Frankenstein', 'Verizon', 100.0, TIMESTAMPADD(MINUTES, 90, CAST(DATESUB(DAYS, 1, FROM_DAYS(UNIX_DATE())) AS TIMESTAMP)));
INSERT INTO transactions (TXN_ID, USERNAME, RECIPIENT, AMOUNT, TS) VALUES (19, 'Frau Blücher', 'Goodwill', 7.0, TIMESTAMPADD(MINUTES, 100, CAST(DATESUB(DAYS, 1, FROM_DAYS(UNIX_DATE())) AS TIMESTAMP)));

CREATE STREAM suspicious_transactions
    WITH (kafka_topic='suspicious_transactions', partitions=1, value_format='JSON') AS
    SELECT T.TXN_ID, T.USERNAME, T.RECIPIENT, T.AMOUNT, T.TS
    FROM transactions T
    INNER JOIN
    suspicious_names S
    ON T.RECIPIENT = S.COMPANY_NAME;

CREATE TABLE accounts_to_monitor
    WITH (kafka_topic='accounts_to_monitor', partitions=1, value_format='JSON') AS
    SELECT TIMESTAMPTOSTRING(WINDOWSTART, 'yyyy-MM-dd HH:mm:ss Z') AS WINDOW_START,
           TIMESTAMPTOSTRING(WINDOWEND, 'yyyy-MM-dd HH:mm:ss Z') AS WINDOW_END,
           USERNAME
    FROM suspicious_transactions
    WINDOW TUMBLING (SIZE 24 HOURS)
    GROUP BY USERNAME
    HAVING COUNT(*) > 3;