#!/usr/bin/env python

import harness_runner
import sys

if len(sys.argv) <= 3:
  harness_runner.execute(sys.argv[1], sys.argv[2])
else:
  harness_runner.execute(sys.argv[1], sys.argv[2], sys.argv[3])
