Now we write a query to concatenate multiple columns. To achieve this, we will use the `-` operator to calculate the difference between two columns.

[source, sql]
----

SELECT FIRST_NAME,
       LAST_NAME,
       CURRENT_PURCHASE - PREVIOUS_PURCHASE as PURCHASE_DIFF <1>
FROM PURCHASE_STREAM
EMIT CHANGES
LIMIT 4;


----

<1> Using the `-` operator to calculate the difference between two columns.

NOTE: The `-` operator expects numerical values.  So if have columns where the numbers are stored as `VARCHAR` you'll have to use a `CAST` operation to convert them to a numerical type, otherwise you'll get an error in your query.


This query should produce the following output:

+++++
<pre class="snippet"><code class="shell">{% include_raw tutorials/column-difference/ksql/code/tutorial-steps/dev/expected-transient-reporting.log %}</code></pre>
+++++

Now that the reporting query works, let's update it to create a continuous query for your reporting scenario:

+++++
<pre class="snippet"><code class="shell">{% include_raw tutorials/column-difference/ksql/code/tutorial-steps/dev/continuous-reporting.sql %}</code></pre>
+++++

We're done with the ksqlDB CLI for now so go ahead and type `exit` to quit.
