////
In this file you describe the Kafka streams topology, and should cover the main points of the tutorial.
The text assumes a method buildTopology exists and constructs the Kafka Streams application.  Feel free to modify the text below to suit your needs.
////

In this tutorial you'll learn about using https://docs.confluent.io/platform/current/streams/developer-guide/dsl-api.html#session-windows[SessionWindows with Kafka Streams].  Session windows are driven by user behavior, as opposed to time.


[source, java]
----

   builder.stream(inputTopic, Consumed.with(Serdes.String(), clicksSerde))
                .groupByKey() <1>
                .windowedBy(SessionWindows.with(Duration.ofMinutes(5)).grace(Duration.ofSeconds(30))) <2>
                .count() <3>
                .toStream()
                .map((windowedKey, count) ->  { <4>
                    String start = timeFormatter.format(windowedKey.window().startTime());
                    String end = timeFormatter.format(windowedKey.window().endTime());
                    String sessionInfo = String.format("Session info started: %s ended: %s with count %s", start, end, count);
                    return KeyValue.pair(windowedKey.key(), sessionInfo);
                })


----

<1> Grouping by key, a prerequisite for aggregation operations
<2> Specifying a session window for the windowing operation
<3> Counting the number of clicks by key per session
<4> Formatting the results.  You probably won't do this in practice, but it's done in this tutorial to make the concept of a session more clear.

For this session window, once there is a period of inactivity of 5 minutes or more for a given key the current session is closed and any new records arriving after that time start a new session.

Session windows aggregate events (by key) into sessions.  A session represents a period of activity followed by inactivity period.  Once the defined time for inactivity elapses, the session is considered closed.  Session windows are a bit different from other window types (hopping, tumbling) because they don't have a fixed window size.  As long as new records arrive for a key within the inactivity gap, the window continues to grow in size, meaning the amount of time the window spans, not the total number of records in the window.  Another way to view session windows is that they are driven by behavior while other window types are solely time based.

_**NOTE:**_ This in this example the incoming records have keys.  If your input topic is not keyed, you'll need to use the https://javadoc.io/static/org.apache.kafka/kafka-streams/2.7.0/org/apache/kafka/streams/kstream/KStream.html#groupBy-org.apache.kafka.streams.kstream.KeyValueMapper-[KStream.groupBy] method and provide a https://javadoc.io/static/org.apache.kafka/kafka-streams/2.7.0/org/apache/kafka/streams/kstream/KeyValueMapper.html[KeyValueMapper] instance to select to key to use for grouping.


That wraps up our discussion for the finer points of the code for this tutorial.  Now create the following file at `src/main/java/io/confluent/developer/SessionWindow.java`

+++++
<pre class="snippet"><code class="java">{% include_raw tutorials/session-windows/kstreams/code/src/main/java/io/confluent/developer/SessionWindow.java %}</code></pre>
+++++
