The second technique for masking data utilizes KSQL's built in `MASK` functions. Here, we retain the customer name and date of birth, but obfuscated:
+++++
<pre class="snippet"><code class="sql">{% include_raw tutorials/masking-data/ksql/code/tutorial-steps/dev/create-purchases-pii-obfuscated.sql %}</code></pre>
+++++
[TIP]
.`MASK` Function Options
====
There are a few types of masking functions and optional parameters that may be of use to you. +

*Optional arguments:* +
`MASK(CUSTOMER_NAME, 'X', 'x', 'n', '-')` +
In the example above, the following types of characters in `CUSTOMER_NAME` would be masked: upper-case letters would become `X`, lower-case letters would become `x`, numbers would become `n`, and other characters would become `-`. This is the default setting if no mask characters are present. Set a given mask character to NULL to prevent any masking of that character type. +

*Other types of `MASK` Functions:* +
KSQL offers a variety of different masking functions that allow you to mask the farthest or nearest _x_ number of characters on right or left. Check out the KSQL documentation link:https://docs.ksqldb.io/en/latest/developer-guide/ksqldb-reference/scalar-functions/#mask[*link here*,window=_blank] for more information.
====