CREATE STREAM purchases_pii_obfuscated AS
  SELECT  MASK(CUSTOMER_NAME) AS CUSTOMER_NAME,
          MASK(DATE_OF_BIRTH) AS DATE_OF_BIRTH,
          ORDER_ID, PRODUCT, ORDER_TOTAL_USD, TOWN, COUNTRY
  FROM PURCHASES;