CREATE STREAM MASKED_PURCHASES AS
  SELECT  MASK(CUSTOMER_NAME) AS CUSTOMER_NAME,
          MASK_RIGHT(DATE_OF_BIRTH,12) AS DATE_OF_BIRTH,
          ORDER_ID, PRODUCT, ORDER_TOTAL_USD, TOWN, COUNTRY
  FROM PURCHASES;