To stream syslog data into a Kafka topic called `syslog`, create the `Dockerfile` below to bundle a Kafka Connect worker with the `kafka-connect-syslog` connector:

++++
<pre class="snippet"><code class="json">{% include_raw tutorials/SSH-attack/confluent/code/tutorial-steps/dev/Dockerfile %}</code></pre>
++++

Build the custom Docker image with this command:

[source,text]
----
docker build \
   -t localbuild/connect_distributed_with_syslog:1.3.4 \
   -f Dockerfile .
----

Next, create a `docker-compose.yml` file with the following content, substituting your Confluent Cloud connection information:

++++
<pre class="snippet"><code class="json">{% include_raw tutorials/SSH-attack/confluent/code/tutorial-steps/dev/docker-compose.yml %}</code></pre>
++++

Run the container with this:

[source,text]
----
docker compose up -d
----

Create a Syslog Source connector configuration file called `connector-syslog.config`:

++++
<pre class="snippet"><code class="json">{% include_raw tutorials/SSH-attack/confluent/code/tutorial-steps/dev/source.json %}</code></pre>
++++

Submit that connector to the connect worker:

[source,text]
----
curl -X POST -H "Content-Type: application/json" --data @connector-syslog.config http://localhost:8083/connectors
----

Now you should have Syslog messages being written to the `syslog` topic in Confluent Cloud.
