SELECT
    EXTRACTJSONFIELD (JSONTypeOne, '$.oneOnlyField') AS SPECIAL_INFO,
    CAST(EXTRACTJSONFIELD (JSONTypeTwo, '$.numberField') AS DOUBLE) AS RUNFLD,
    EXTRACTJSONFIELD (JSONTypeThree, '$.fieldD') AS DESCRIPTION
FROM
    DATA_STREAM
EMIT CHANGES
LIMIT 4;
