To complete this tutorial, you'll need to also create an abstract class that we will extend to process messages as we consume them. This
abstract class, `ConsumerRecordHandler`, encapsulates tracking the number of records processed, which will be useful later on when we run
performance tests and want to terminate the test application after consuming an expected number of records.

First create the abstract class at `src/main/java/io/confluent/developer/ConsumerRecordHandler.java`

+++++
<pre class="snippet"><code class="java">{% include_raw tutorials/confluent-parallel-consumer-application/kafka/code/src/main/java/io/confluent/developer/ConsumerRecordHandler.java %}</code></pre>
+++++

Using this abstract class will make it easier to change how you want to work with a `ConsumerRecord` without having to modify all of your existing code.

Next you'll extend the `ConsumerRecordHandler` abstract class with a concrete class named `FileWritingRecordHandler`. Copy the following into file `src/main/java/io/confluent/developer/FileWritingRecordHandler.java`:

+++++
<pre class="snippet"><code class="java">{% include_raw tutorials/confluent-parallel-consumer-application/kafka/code/src/main/java/io/confluent/developer/FileWritingRecordHandler.java %}</code></pre>
+++++

Let's take a peek under the hood at this class's `processRecordImpl` method, which gets calls for each record consumed:

[source, java]
.FileWritingRecordHandler.processRecordImpl
----
  @Override
  protected void processRecordImpl(final ConsumerRecord<String, String> consumerRecord) {
    try {
      Files.write(path, singletonList(consumerRecord.value()), CREATE, WRITE, APPEND); // <1>
    } catch (IOException e) {
      throw new RuntimeException("unable to write record to file", e);
    }
  }
----
<1> Simply write the record value to a file.

In practice you're certain to perform a more realistic task for each record.

Finally, create a utility class `PropertiesUtil` that we use in our consumer application to load Kafka Consumer and
application-specific properties. We'll also use this class in the two performance testing applications that we will create
later in this tutorial.

Go ahead and create the `src/main/java/io/confluent/developer/PropertiesUtil.java` file:

+++++
<pre class="snippet"><code class="java">{% include_raw tutorials/confluent-parallel-consumer-application/kafka/code/src/main/java/io/confluent/developer/PropertiesUtil.java %}</code></pre>
+++++