CREATE TABLE TRIGGERED_ALERTS AS
    SELECT
        ID,
        TIMESTAMPTOSTRING(WindowStart(), 'HH:mm:ss') AS START_PERIOD,
        TIMESTAMPTOSTRING(WindowEnd(), 'HH:mm:ss') AS END_PERIOD,
        SUM(READING)/COUNT(READING) AS AVG_READING
    FROM TEMPERATURE_READINGS
    WINDOW HOPPING (SIZE 10 SECONDS, ADVANCE BY 5 SECONDS)
    GROUP BY ID HAVING SUM(READING)/COUNT(READING) < 45;

CREATE STREAM RAW_ALERTS (ID VARCHAR, START_PERIOD VARCHAR, END_PERIOD VARCHAR, AVG_READING BIGINT)
    WITH (KAFKA_TOPIC = 'TRIGGERED_ALERTS',
          VALUE_FORMAT = 'JSON');

CREATE STREAM ALERTS AS
    SELECT
        ID,
        START_PERIOD,
        END_PERIOD,
        AVG_READING
    FROM RAW_ALERTS
    PARTITION BY ID;
