SELECT
    ID,
    TIMESTAMPTOSTRING(WindowStart(), 'HH:mm:ss') AS START_PERIOD,
    TIMESTAMPTOSTRING(WindowEnd(), 'HH:mm:ss') AS END_PERIOD,
    SUM(READING)/COUNT(READING) AS AVG_READING
FROM TEMPERATURE_READINGS
WINDOW HOPPING (SIZE 10 MINUTES, ADVANCE BY 5 MINUTES)
GROUP BY ID HAVING SUM(READING)/COUNT(READING) < 45 LIMIT 3;
