The first thing we do is to create a stream `TRANSACTION_STREAM` based off stock purchase transactions topic `financial_txns`. Within the `CREATE STREAM` statement, you'll use a `STRUCT` keyword to define each nested object.

To quote the https://docs.ksqldb.io/en/latest/developer-guide/syntax-reference/#struct[ksqlDB documentation] "A struct represents strongly typed structured, or nested, data. A struct is an ordered collection of named fields that have a specific type."

Please note that the example in this tutorial, the nested JSON structures have the same number fields for every transaction. If you have a situation where the nested objects contain a variable number of fields then you'll need to use the https://docs.ksqldb.io/en/latest/developer-guide/syntax-reference/#map[ksqlDB MAP function] as https://rmoff.net/2020/10/07/ksqldb-how-to-model-a-variable-number-of-fields-in-a-nested-value-struct/[described in this blog post].



[source, sql]
----
CREATE STREAM TRANSACTION_STREAM (
	      id VARCHAR,
              transaction STRUCT<num_shares INT,     <1>
             	                  amount DOUBLE,
             	                  txn_ts VARCHAR,
             	                  customer STRUCT<first_name VARCHAR,  <2>
             	                                  last_name VARCHAR,
             	                                  id INT,
             	                                  email VARCHAR>,
                                   company STRUCT<name VARCHAR,        <3>
                                                  ticker VARCHAR,
                                                  id VARCHAR,
                                                  address VARCHAR>>)
 WITH (KAFKA_TOPIC='financial_txns',
       VALUE_FORMAT='JSON',
       PARTITIONS=1);

----

<1> The entire stock transaction is nested so we create a STRUCT
<2> The nested customer fields
<3> The nested company fields

Go ahead and create the stream now by pasting this statement into the ksqlDB window you opened at the beginning of this step.  After you've created the stream, quit the ksqlDB CLI for now by typing `exit`.
