SELECT TIMESTAMPTOSTRING(L.ROWTIME,'yyyy-MM-dd HH:mm:ss','Europe/London') AS EVENT_TS, 
       LOCATION, 
       ENGINE_TEMPERATURE as TEMP, 
       AVERAGE_RPM
  FROM LOCATIONS L 
       INNER JOIN SENSOR_READINGS SR WITHIN 1 HOUR ON L.VEHICLE_ID=SR.VEHICLE_ID
EMIT CHANGES LIMIT 10;
