////
In this file you describe the Kafka streams topology, and should cover the main points of the tutorial.
The text assumes a method buildTopology exists and constructs the Kafka Streams application.  Feel free to modify the text below to suit your needs.
////

Before you create the Kafka Streams application let's go over the key points.  In this tutorial you'll learn about using https://javadoc.io/doc/org.apache.kafka/kafka-streams/latest/org/apache/kafka/streams/kstream/SlidingWindows.html[SlidingWindows] for https://docs.confluent.io/platform/current/streams/developer-guide/dsl-api.html#aggregating[aggregation operations].  Incoming record timestamps drive the window behavior, and the time difference between records plus a grace period for out-of-order records (both are user defined) drives the size of the window.

[source, java]
----

   builder.stream(tempReadingTopic, Consumed.with(Serdes.String(), temReadingSerde))
                .groupByKey() <1>
                .windowedBy(SlidingWindows.withTimeDifferenceAndGrace(Duration.ofSeconds(1), Duration.ofSeconds(1))) <2>
                .aggregate(TempAverage::new, (k, tr, ave) -> { <3>
                    ave.setNumReadings(ave.getNumReadings() +1);
                    ave.setTotal(ave.getTotal() + tr.getTemp());
                    return ave;
                }, Materialized.with(Serdes.String(), tempAveSerde))

----

<1> Grouping by key, a prerequisite for aggregation operations
<2> Specifying a sliding window for the windowing operation
<3> The aggregation operation which sums the temperature and keeps a total count of the readings

As the window "slides" over the record stream, a new window is created each time a record enters or exits the window.  Records that arrive after grace period are dropped. A window closes when `stream-time` exceeds the `window-end` + `grace-period`

You can get similar behavior in hopping windows by defining a short advance time. But this will result in poor performance because hopping windows will create many overlapping, possibly redundant windows.  Performing aggregation operations over redundant windows costs CPU time, which can be expensive.  Sliding windows only create windows containing distinct items, and perform calculations on these is more efficient. Additionally, sliding windows are inclusive on both the start and end time vs. hopping windows being inclusive only on the start time.

NOTE: The concept of `stream-time` is the largest timestamp processed by Kafka Streams at a given point in time.  A grace-period is the amount of time you're allowing out-of-order records to be included in a window.

That wraps up our discussion for the finer points of the code for this tutorial.  Now create the following file at `src/main/java/io/confluent/developer/SlidingWindow.java`

+++++
<pre class="snippet"><code class="java">{% include_raw tutorials/sliding-windows/kstreams/code/src/main/java/io/confluent/developer/SlidingWindow.java %}</code></pre>
+++++
