/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.confluent.developer.serialization;

import org.apache.kafka.clients.admin.AdminClient;
import org.apache.kafka.clients.admin.NewTopic;
import org.apache.kafka.streams.KeyValue;
import org.apache.kafka.streams.StreamsBuilder;
import org.apache.kafka.streams.StreamsConfig;
import org.apache.kafka.streams.Topology;
import org.apache.kafka.streams.kstream.Consumed;
import org.apache.kafka.streams.kstream.KStream;
import org.apache.kafka.streams.kstream.Produced;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Properties;

import io.confluent.developer.avro.Movie;
import io.confluent.developer.serialization.util.MovieUtil;
import io.confluent.kafka.serializers.AbstractKafkaAvroSerDeConfig;
import io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde;

import static io.confluent.developer.serialization.serde.MovieJsonSerde.MovieJsonSerde;
import static org.apache.kafka.common.serialization.Serdes.Long;
import static org.apache.kafka.common.serialization.Serdes.String;

public abstract class SerializationRecipe implements IRecipe {

  @Override
  public Properties buildStreamsProperties(Properties envProps) {
    Properties props = new Properties();

    props.put(StreamsConfig.APPLICATION_ID_CONFIG, envProps.getProperty("application.id"));
    props.put(StreamsConfig.BOOTSTRAP_SERVERS_CONFIG, envProps.getProperty("bootstrap.servers"));
    props.put(StreamsConfig.DEFAULT_KEY_SERDE_CLASS_CONFIG, String().getClass());
    props.put(StreamsConfig.DEFAULT_VALUE_SERDE_CLASS_CONFIG, String().getClass());
    props.put(AbstractKafkaAvroSerDeConfig.SCHEMA_REGISTRY_URL_CONFIG, envProps.getProperty("schema.registry.url"));
    props.put(StreamsConfig.CACHE_MAX_BYTES_BUFFERING_CONFIG, 0);

    return props;
  }

  @Override
  public void createTopics(Properties envProps) {
    Map<String, Object> config = new HashMap<>();
    config.put("bootstrap.servers", envProps.getProperty("bootstrap.servers"));
    AdminClient client = AdminClient.create(config);

    List<NewTopic> topics = new ArrayList<>();

    topics.add(new NewTopic(
        envProps.getProperty("input.topic.name"),
        Integer.parseInt(envProps.getProperty("input.topic.partitions")),
        Short.parseShort(envProps.getProperty("input.topic.replication.factor"))));

    topics.add(new NewTopic(
        envProps.getProperty("output.avro.movies.topic.name"),
        Integer.parseInt(envProps.getProperty("output.avro.movies.topic.partitions")),
        Short.parseShort(envProps.getProperty("output.avro.movies.topic.replication.factor"))));

    topics.add(new NewTopic(
        envProps.getProperty("output.json.movies.topic.name"),
        Integer.parseInt(envProps.getProperty("output.json.movies.topic.partitions")),
        Short.parseShort(envProps.getProperty("output.json.movies.topic.replication.factor"))));

    client.createTopics(topics);
    client.close();
  }
  
  SpecificAvroSerde<Movie> movieAvroSerde(Properties envProps) {
    SpecificAvroSerde<Movie> movieAvroSerde = new SpecificAvroSerde<>();
    final HashMap serdeConfig = new HashMap() {{
      put(AbstractKafkaAvroSerDeConfig.SCHEMA_REGISTRY_URL_CONFIG,
          envProps.getProperty("schema.registry.url"));
    }};
    movieAvroSerde.configure(serdeConfig, false);
    return movieAvroSerde;
  }

  public static void main(String[] args) {
    if (args.length < 1) {
      throw new IllegalArgumentException(
          "This program takes one argument: the path to an environment configuration file.");
    }

    new SerializationRecipe() {
      @Override
      public Topology buildTopology(Properties envProps) {

        final String inputTopicName = envProps.getProperty("input.topic.name");
        final String avroTopicName = envProps.getProperty("output.avro.movies.topic.name");
        final String jsonTopicName = envProps.getProperty("output.json.movies.topic.name");

        final StreamsBuilder builder = new StreamsBuilder();

        final KStream<Long, String> rawMoviesStream =
            builder.stream(inputTopicName, Consumed.with(Long(), String()));

        final KStream<Long, Movie> avroMoviesStream =
            rawMoviesStream
                .mapValues(MovieUtil::parseMovie)
                .map((key, movie) -> new KeyValue<>(movie.getMovieId(), movie));

        // write movie data in avro format
        avroMoviesStream.to(avroTopicName, Produced.with(Long(), movieAvroSerde(envProps)));

        // write movie data in json format
        avroMoviesStream.to(jsonTopicName, Produced.with(Long(), MovieJsonSerde()));

        return builder.build();
      }
    }.runRecipe(args[0]);
  }
}

