CREATE STREAM PURCHASE_STREAM (
                ID VARCHAR,
                      PREVIOUS_PURCHASE DOUBLE,
                      CURRENT_PURCHASE DOUBLE,
                      TXN_TS VARCHAR,
                      FIRST_NAME VARCHAR,
                      LAST_NAME  VARCHAR)

 WITH (KAFKA_TOPIC='customer_purchases',
       VALUE_FORMAT='JSON',
       PARTITIONS=1);
 

CREATE STREAM PURCHASE_HISTORY_STREAM AS
  SELECT FIRST_NAME,
       LAST_NAME,
       CURRENT_PURCHASE - PREVIOUS_PURCHASE as PURCHASE_DIFF
FROM PURCHASE_STREAM;