////
In this file you describe the Kafka streams topology, and should cover the main points of the tutorial.
The text assumes a method buildTopology exists and constructs the Kafka Streams application.  Feel free to modify the text below to suit your needs.
////

To complete this tutorial, you'll need to also create an interface for a helper class.


First create the interface at `src/main/java/io/confluent/developer/ConsumerRecordsHandler.java`

+++++
<pre class="snippet"><code class="java">{% include_raw tutorials/kafka-consumer-application/kafka/code/src/main/java/io/confluent/developer/ConsumerRecordsHandler.java %}</code></pre>
+++++

Using an interface will make it easier to change how you want to work with `ConsumerRecords` without having to modify all of your existing code.



Next you'll create an implementation of the `ConsumerRecordsHandler` interface named `FileWritingRecordsHandler`, but before you do that, let's take a peek under the hood to understand how the helper class works.

The `FileWritingRecordsHandler` is a simple class that writes values of consumed records to a file, it's worth a quick review of the `process` method:

[source, java]
.FileWritingRecordsHandler.process
----
 @Override
  public void process(final ConsumerRecords<String, String> consumerRecords) {
    final List<String> valueList = new ArrayList<>();
    consumerRecords.forEach(record -> valueList.add(record.value())); // <1>
    if (!valueList.isEmpty()) {  //<2>
      try {
        Files.write(path, valueList, StandardOpenOption.CREATE, StandardOpenOption.WRITE, StandardOpenOption.APPEND);  //<3>
      } catch (IOException e) {
        throw new RuntimeException(e);
      }
    }
  }
----
<1> Iterate over all of the records and store each record's `value` in a `List`
<2> If the `List` isn't empty, let's do something!
<3> Pass the `List&lt;String&gt;` of records to the `Files.write()` method


In practice you're certain to do a more realistic workload.

Now go ahead and create the `src/main/java/io/confluent/developer/FileWritingRecordsHandler.java` file:

+++++
<pre class="snippet"><code class="java">{% include_raw tutorials/kafka-consumer-application/kafka/code/src/main/java/io/confluent/developer/FileWritingRecordsHandler.java %}</code></pre>
+++++
