CREATE STREAM DATA_STREAM ( 
  JSONTypeOne VARCHAR, 
  JSONTypeTwo VARCHAR, 
  JSONTypeThree VARCHAR
  )   

 WITH (KAFKA_TOPIC='source_data',
       VALUE_FORMAT='JSON',
       PARTITIONS=1);


CREATE STREAM SUMMARY_REPORTS AS
   SELECT
    EXTRACTJSONFIELD (JSONTypeOne, '$.oneOnlyField') AS SPECIAL_INFO,
    CAST(EXTRACTJSONFIELD (JSONTypeTwo, '$.numberField') AS DOUBLE) AS RUNFLD,
    EXTRACTJSONFIELD (JSONTypeThree, '$.fieldD') AS DESCRIPTION
FROM
    DATA_STREAM;