Here you'll build a performance test application based on the Confluent Parallel Consumer. This test reuses a couple of classes
that we created previously: `PropertiesUtil` for loading consumer and application-specific properties, and `SleepingRecordHandler`
for simulating a nontrivial workload per-record just as we did in `MultithreadedKafkaConsumerPerfTest`. Please rewind
and create these if you skipped the parts of the tutorial that create these two classes.

Because the Confluent Parallel Consumer API is much lighter weight than the lift required to multi-thread `KafkaConsumer` instances
per partition, let's knock out the entire thing in one class. Create the file `src/main/java/io/confluent/developer/ParallelConsumerPerfTest.java`:

+++++
<pre class="snippet"><code class="java">{% include_raw tutorials/confluent-parallel-consumer-application/kafka/code/src/main/java/io/confluent/developer/ParallelConsumerPerfTest.java %}</code></pre>
+++++

Take a look at the code and note the simplicity. Most of the code is for properties file handling and tracking progress. The interesting part relevant to the Confluent Parallel Consumer
is in the four-line `runConsume()` method:

[source, java]
.ParallelConsumerPerfTest.runConsume
----
  private void runConsume(final Properties appProperties) {
    parallelConsumer.subscribe(Collections.singletonList(appProperties.getProperty("input.topic.name")));
    parallelConsumer.poll(context -> {
      recordHandler.processRecord(context.getSingleConsumerRecord());
    });
  }
----

Bellisimo!
