Now we write a query where we select the desired fields but we don't have them listed in a comma separated list.  Instead we use the `+` operator between the fields causting them to get concatenated together.

[source, sql]
----

SELECT FIRST_NAME + ' ' + LAST_NAME +
       ' purchased ' +
       CAST(NUM_SHARES AS VARCHAR) + <1>
       ' shares of ' +
       SYMBOL AS SUMMARY
FROM ACTIVITY_STREAM
EMIT CHANGES
LIMIT 4;


----

<1> The NUM_SHARES field is an `INT` so we need to cast it to a `VARCHAR` as `concatenate` only works with `STRING` types

NOTE: You can also select fields you don't want to concatenate.  In that case you use a comma to separate the field from those you concatenate together.  For example
SELECT field_1, field_2, field_3 + field_4

This query should produce the following output:

+++++
<pre class="snippet"><code class="shell">{% include_raw tutorials/ksql-concatenation-columns/ksql/code/tutorial-steps/dev/expected-transient-reporting.log %}</code></pre>
+++++

Now that the reporting query works, let's update it to create a continous query for your reporting scenario

+++++
<pre class="snippet"><code class="shell">{% include_raw tutorials/ksql-concatenation-columns/ksql/code/tutorial-steps/dev/continuous-reporting.sql %}</code></pre>
+++++

We're done with the ksqlDB CLI for now so go ahead and type `exit` to quit.
