INSERT INTO transactions (TXN_ID, USERNAME, RECIPIENT, AMOUNT) VALUES (9900, 'Abby Normal', 'Verizon', 22.0);
INSERT INTO transactions (TXN_ID, USERNAME, RECIPIENT, AMOUNT) VALUES (12, 'Victor von Frankenstein', 'Tattered Cover', 7.0);
INSERT INTO transactions (TXN_ID, USERNAME, RECIPIENT, AMOUNT) VALUES (13, 'Frau Blücher', 'Peebles', 70.0);
INSERT INTO transactions (TXN_ID, USERNAME, RECIPIENT, AMOUNT) VALUES (9903, 'Abby Normal', 'Verizon', 61.0);
INSERT INTO transactions (TXN_ID, USERNAME, RECIPIENT, AMOUNT) VALUES (9901, 'Abby Normal', 'Spirit Halloween', 83.0);
INSERT INTO transactions (TXN_ID, USERNAME, RECIPIENT, AMOUNT) VALUES (9902, 'Abby Normal', 'Spirit Halloween', 46.0);
INSERT INTO transactions (TXN_ID, USERNAME, RECIPIENT, AMOUNT) VALUES (9904, 'Abby Normal', 'Spirit Halloween', 59.0);
INSERT INTO transactions (TXN_ID, USERNAME, RECIPIENT, AMOUNT) VALUES (6, 'Victor von Frankenstein', 'Confluent Cloud', 21.0);
INSERT INTO transactions (TXN_ID, USERNAME, RECIPIENT, AMOUNT) VALUES (18, 'Frau Blücher', 'Target', 70.0);
INSERT INTO transactions (TXN_ID, USERNAME, RECIPIENT, AMOUNT) VALUES (7, 'Victor von Frankenstein', 'Verizon', 100.0);
INSERT INTO transactions (TXN_ID, USERNAME, RECIPIENT, AMOUNT) VALUES (19, 'Frau Blücher', 'Goodwill', 7.0);
