INSERT INTO MOVIES_JSON (MOVIE_ID, TITLE, RELEASE_YEAR) VALUES (1, 'Lethal Weapon', 1992);
INSERT INTO MOVIES_JSON (MOVIE_ID, TITLE, RELEASE_YEAR) VALUES (2, 'Die Hard', 1988);
INSERT INTO MOVIES_JSON (MOVIE_ID, TITLE, RELEASE_YEAR) VALUES (3, 'Predator', 1997);