CREATE STREAM MOVIES_JSON (movie_id BIGINT, title VARCHAR, release_year INT) 
    WITH (KAFKA_TOPIC='json-movies',
        PARTITIONS=1, 
        VALUE_FORMAT='JSON');

CREATE STREAM MOVIES_AVRO WITH (VALUE_FORMAT='AVRO', KAFKA_TOPIC='avro-movies') AS SELECT * FROM MOVIES_JSON;
