In a similar manner, populate the ratings stream:

+++++
<pre class="snippet"><code class="sql">{% include_raw tutorials/joining-stream-table/ksql/code/tutorial-steps/dev/populate-ratings.sql %}</code></pre>
+++++

[NOTE]
.Populating Data
====
One fundamental operation for working with tables is populating them with data. There are a number of ways to do this:

 * Use ksqlDB's `INSERT INTO VALUES` syntax.
 * Use the Apache Kafka® clients to write data to the underlying topics.
 * Use connectors to source data from external systems.

This tutorial uses ksqlDB `INSERT INTO VALUES` syntax. For an example on how to use the Apache Kafka® clients to write data to the underlying topics, see link:{{ "creating-first-apache-kafka-producer-application/confluent.html" | relative_url }}[*building your first Kafka producer application*] and for an example on how to use connectors to source data from external systems, see link:{{ "connect-add-key-to-source/ksql.html" | relative_url }}[*creating a ksqlDB table from PostgreSQL data using Kafka Connect*].
====
