The first thing we do is to create a stream `DATA_STREAM` based off the topic `source_data`. Within the `CREATE STREAM` statement, you'll use a `VARCHAR` keyword to define each of outer most element of the JSON types.

[source, sql]
----
CREATE STREAM DATA_STREAM (
  JSONType1 VARCHAR,          <1>
  JSONType2 VARCHAR,          <2>
  JSONType3 VARCHAR         <3>
  )

 WITH (KAFKA_TOPIC='source_data',
       VALUE_FORMAT='JSON',
       PARTITIONS=1);

----

<1> Defining outer JSON element of type one as VARCHAR
<2> Defining outer JSON element of type two as VARCHAR
<3> Defining outer JSON element of type three as VARCHAR

Go ahead and create the stream now by pasting this statement into the ksqlDB window you opened at the beginning of this step.  After you've created the stream, quit the ksqlDB CLI for now by typing `exit`.

By defining outer most element of the different JSON objects as `VARCHAR`, we're setting ourselves up with the ability to extract arbitrary fields on the different JSON records as we'll see in an upcoming section.  But first we need to add some records to the `source_data` topic which we'll do in the next step.
