Let's say you have a topic `source_data`, that contains JSON.  But each nested JSON object has a different structure.  Addtionally, in each object there is a mix of types within the values.

They each have one field in common that you want to pull out in a query and you don't care about the structure of the individual JSON objects

[source, json]
----
{
  "JSONTypeOne": {
    "fieldA": "some data",
    "numberField": 1.001,
    "oneOnlyField": "more data", <1>
    "randomField": "random data"
  },

  "JSONTypeTwo": {
    "fieldA": "data",
    "fieldB": "b-data",
    "numberField": 98.6   <2>
  },

  "JSONTypeThree": {
    "fieldA": "data",
    "fieldB": "b-data",
    "numberField": 98.6,
    "fieldC": "data",
    "fieldD": "D-data"    <3>
  }
----
<1> The field you want from JSONTypeOne
<2> The field you want from JSONTypeTwo
<3> The field you want form JSONTypeThree

The key to approaching this problem is having some way to generically model each structure, without having to know details beyond the name of the field you want to extract.
Since there is varying number of fields you can't use https://docs.ksqldb.io/en/latest/developer-guide/syntax-reference/#struct[the ksqlDB STRUCT] and because there is a mix of types in the values https://docs.ksqldb.io/en/latest/developer-guide/syntax-reference/#map[using the ksqlDB map function] isn't an option either.
