Let's say you have a Kafka topic `source_data` that contains JSON-formatted data.  But each nested JSON object has a different structure.  Additionally, within each object the values have a mix of types.

They each have a field that you want to pull out in a query and you don't care about the structure of the individual JSON objects

[source, json]
----
  "JSONType1": {
    "fieldA": "some data",
    "numberField": 1.001,
    "oneOnlyField": "more data", <1>
    "randomField": "random data"
  }
----

[source, json]
----

  "JSONType2": {
    "fieldA": "data",
    "fieldB": "b-data",
    "numberField": 98.6   <2>
  }
----

[source, json]
----

  "JSONType3": {
    "fieldA": "data",
    "fieldB": "b-data",
    "numberField": 98.6,
    "fieldC": "data",
    "fieldD": "D-data"    <3>
  }
----
<1> The field you want from JSONType1
<2> The field you want from JSONType2
<3> The field you want from JSONType3

The key to approaching this problem is having some way to generically model each structure, without having to know details beyond the name of the field you want to extract.
Since there is varying number of fields you can't use https://docs.ksqldb.io/en/latest/developer-guide/syntax-reference/#struct[the ksqlDB STRUCT] and because there is a mix of types in the values https://docs.ksqldb.io/en/latest/developer-guide/syntax-reference/#map[using the ksqlDB map function] isn't an option either.
