INSERT INTO MOVIES (ID, TITLE, RELEASE_YEAR) VALUES (48, 'Aliens', 1986);
INSERT INTO MOVIES (ID, TITLE, RELEASE_YEAR) VALUES (294, 'Die Hard', 1998);
INSERT INTO MOVIES (ID, TITLE, RELEASE_YEAR) VALUES (128, 'The Big Lebowski', 1998);
INSERT INTO MOVIES (ID, TITLE, RELEASE_YEAR) VALUES (42, 'The Godfather', 1998);
