INSERT INTO LEAD_ACTOR (TITLE, ACTOR_NAME) VALUES ('Aliens','Sigourney Weaver');
INSERT INTO LEAD_ACTOR (TITLE, ACTOR_NAME) VALUES ('Die Hard','Bruce Willis');
INSERT INTO LEAD_ACTOR (TITLE, ACTOR_NAME) VALUES ('The Big Lebowski','Jeff Bridges');
INSERT INTO LEAD_ACTOR (TITLE, ACTOR_NAME) VALUES ('The Godfather','Al Pacino');
