kind: kstreams
steps:
  - name: make the prod props file
    change_directory: filter-events
    action: make_file
    file: configuration/prod.properties

  - name: build the image
    action: execute
    file: recipe-steps/prod/build-image.sh
