SELECT
    MESSAGE->DESERIALIZATIONERROR->ERRORMESSAGE,
    encode(MESSAGE->DESERIALIZATIONERROR->RECORDB64, 'base64', 'utf8') AS MSG,
    MESSAGE->DESERIALIZATIONERROR->CAUSE
  FROM KSQL_PROCESSING_LOG
  EMIT CHANGES
  LIMIT 1;
