INSERT INTO MOVIES (ROWKEY, ID, TITLE, RELEASE_YEAR) VALUES ('Aliens', 48, 'Aliens', 1986);
INSERT INTO MOVIES (ROWKEY, ID, TITLE, RELEASE_YEAR) VALUES ('Die Hard', 294, 'Die Hard', 1998);
INSERT INTO MOVIES (ROWKEY, ID, TITLE, RELEASE_YEAR) VALUES ('The Big Lebowski', 128, 'The Big Lebowski', 1998);
INSERT INTO MOVIES (ROWKEY, ID, TITLE, RELEASE_YEAR) VALUES ('The Godfather', 42, 'The Godfather', 1998);
