-- Enrich Survey Responses with Respondent Data
CREATE STREAM SURVEY_RESPONSES_ENRICHED WITH (
    KAFKA_TOPIC = 'survey-responses-enriched', 
    VALUE_FORMAT = 'JSON', 
    KEY_FORMAT = 'KAFKA',
    PARTITIONS = 6
) AS 
SELECT 
    RESPONSES.RESPONDENT_ID AS RESPONDENT_ID,
    RESPONSES.SURVEY_ID,
    RESPONSES.SURVEY_QUESTION,
    RESPONSES.SURVEY_RESPONSE,
    RESPONDENTS.NAME,
    RESPONDENTS.TEAM
FROM SURVEY_RESPONSES RESPONSES 
INNER JOIN SURVEY_RESPONDENTS_MASKED RESPONDENTS 
ON RESPONSES.RESPONDENT_ID = RESPONDENTS.RESPONDENT_ID
EMIT CHANGES;