-- Mask Respondent Data
CREATE TABLE SURVEY_RESPONDENTS_MASKED WITH (
    KAFKA_TOPIC = 'survey-respondents-masked', 
    VALUE_FORMAT = 'JSON', 
    KEY_FORMAT = 'KAFKA',
    PARTITIONS = 6
) AS 
SELECT
    RESPONDENT_ID, 
    NAME,
    TEAM, 
    MASK(EMAIL) AS EMAIL, 
    MASK(ADDRESS) AS ADDRESS
FROM SURVEY_RESPONDENTS
EMIT CHANGES;