-- Fetch Results Live
CREATE TABLE SURVEY_RESULTS_LIVE WITH (
    KAFKA_TOPIC = 'survey-results-live', 
    VALUE_FORMAT = 'JSON', 
    KEY_FORMAT = 'KAFKA',
    PARTITIONS = 6
) AS 
SELECT
    SURVEY_QUESTION,
    HISTOGRAM(SURVEY_RESPONSE) AS RESULTS
FROM SURVEY_RESPONSES_ENRICHED
GROUP BY SURVEY_QUESTION
EMIT CHANGES;

-- Fetch Results Windowed Per Team
CREATE TABLE SURVEY_RESULTS_WINDOWED WITH (
    KAFKA_TOPIC = 'survey-results-windowed', 
    VALUE_FORMAT = 'JSON', 
    KEY_FORMAT = 'KAFKA',
    PARTITIONS = 6
) AS 
SELECT
    SURVEY_QUESTION,
    HISTOGRAM(TEAM) AS TEAMS
FROM SURVEY_RESPONSES_ENRICHED
WINDOW TUMBLING (SIZE 24 HOURS)
GROUP BY SURVEY_QUESTION
EMIT FINAL;