INSERT INTO pages (customer, time, page_id, page) VALUES (44, UNIX_TIMESTAMP(), '1001', '/market/page1.html');
INSERT INTO pages (customer, time, page_id, page) VALUES (89, UNIX_TIMESTAMP(), '1001', '/market/page1.html');
INSERT INTO pages (customer, time, page_id, page) VALUES (44, UNIX_TIMESTAMP(), '1020', '/market/page20.html');
INSERT INTO pages (customer, time, page_id, page) VALUES (89, UNIX_TIMESTAMP(), '1002', '/market/page2.html');
INSERT INTO pages (customer, time, page_id, page) VALUES (89, UNIX_TIMESTAMP(), '1037', '/market/page37.html');
INSERT INTO pages (customer, time, page_id, page) VALUES (44, UNIX_TIMESTAMP(), '1600', '/cart/checkout.html');
INSERT INTO pages (customer, time, page_id, page) VALUES (89, UNIX_TIMESTAMP(), '1600', '/cart/checkout.html');
INSERT INTO pages (customer, time, page_id, page) VALUES (44, UNIX_TIMESTAMP(), '1020', '/market/page20.html');
INSERT INTO pages (customer, time, page_id, page) VALUES (89, UNIX_TIMESTAMP(), '1002', '/market/page2.html');
